/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORT0_25 (coord A6), P0_25/J2[12]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_FC1_CLK_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_FC1_CLK_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_FC1_CLK_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT0_26 (coord F10), P0_26/J2[10]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_FC1_MISO_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_FC1_MISO_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_FC1_MISO_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORT0_24 (coord B6), P0_24/SJ7[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_FC1_MOSI_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_FC1_MOSI_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_FC1_MOSI_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORT0_27 (coord E10), P0_27/SJ6[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_FC1_CS_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_FC1_CS_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_FC1_CS_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_31 (coord D7), P0_31/J1[16]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_NAFE_RST_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_NAFE_RST_GPIO_PIN 31U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_NAFE_RST_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_NAFE_RST_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_NAFE_RST_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_NAFE_RST_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORT1_2 (coord C4), P1_2/SJ4[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ADC_SYNC_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ADC_SYNC_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ADC_SYNC_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ADC_SYNC_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ADC_SYNC_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ADC_SYNC_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT0_30 (coord E7), P0_30/SJ2[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_NAFE_DRDY_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_NAFE_DRDY_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_NAFE_DRDY_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_NAFE_DRDY_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_NAFE_DRDY_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_NAFE_DRDY_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name PORT1_23 (coord M4), P1_23/J9[23]/SJ1[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_NAFE_nINT_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_NAFE_nINT_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_NAFE_nINT_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_NAFE_nINT_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_NAFE_nINT_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_NAFE_nINT_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name PORT0_29 (coord F8), P0_29/J1[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_TEST_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_TEST_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_TEST_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_TEST_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_TEST_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_TEST_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORT0_1 (coord A16), P0_1/SWCLK/J23[4]/D16[5]/J22[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT0_0 (coord A17), P0_0/SWDIO/J23[2]/D16[6]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                         /* @} */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void);

/*! @name PORT1_2 (coord C4), P1_2/SJ4[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_BLUE_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT0_10 (coord B12), P0_10/SJ5[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_RED_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RED_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT0_27 (coord E10), P0_27/SJ6[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN 27U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PORT0_6 (coord C14), P0_6/J23[7]/SW3[3]/SW3[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_23 (coord B7), P0_23/SJ9[1]/SW2[3]/SW2[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW2_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
